"""Transfer-matrix heatmap (CNN), house style. Columns are near-constant: the
target sets the score, the source barely moves it. (The confound figure is
generated by make_fig_confound.py at n=20; the old n=8 confound/residual panels
were removed from here to avoid clobbering it.)"""
import matplotlib; matplotlib.use("Agg")
import json
import os as _os
import sys as _sys

import matplotlib.pyplot as plt
import numpy as np

_REPO = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))  # for figstyle
import figstyle as fs; fs.use_style()

reg = ["south_asia", "ssa", "east_asia", "andes", "mena", "sea", "eeca", "oceania"]
lab = ["South Asia", "Sub-Sah.\nAfrica", "East Asia", "Andes", "MENA", "SE Asia",
       "E.Eur/\nC.Asia", "Oceania"]
m = json.load(open(_os.path.join(_REPO, "results/metrics/transfer_matrix_cnn.json")))
srcs = [s for s in m if all(m[s].get(r) is not None for r in reg)]
slab = [("CONUS" if s == "conus" else lab[reg.index(s)].replace("\n", " ")) for s in srcs]
M = np.array([[m[s][r] for r in reg] for s in srcs])

fig, ax = plt.subplots(figsize=(6.2, 5.0))
im = ax.imshow(M, cmap="viridis", aspect="auto", vmin=0.15, vmax=0.45)
ax.set_xticks(range(len(reg))); ax.set_xticklabels(lab, rotation=40, ha="right", fontsize=7)
ax.set_yticks(range(len(srcs))); ax.set_yticklabels(slab, fontsize=7)
ax.set_xlabel("target region  (evaluated on)"); ax.set_ylabel("source region  (trained on)")
for i in range(len(srcs)):
    for j in range(len(reg)):
        ax.text(j, i, f"{M[i,j]:.2f}", ha="center", va="center",
                color="white" if M[i, j] < 0.33 else fs.C["ink"], fontsize=6)
cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
cb.set_label("figure of merit", fontsize=8); cb.ax.tick_params(labelsize=7)
cb.outline.set_linewidth(0.6)
ax.set_title("Columns are flat: the target sets the score, not the source", fontsize=9, pad=6)
for sp in ax.spines.values():
    sp.set_visible(True); sp.set_linewidth(0.6); sp.set_edgecolor("#999999")
fig.tight_layout(); fig.savefig(_os.path.join(_REPO, "figures", "fig_matrix.pdf"))
